global:
  scrape_interval: 15s

scrape_configs:

  - job_name: 'school-api'
    scheme: http
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['school-api:27017']
        labels:
          application: 'school-api'